theme: jekyll-theme-minimal
title: Tian Cai's portfolio page
description: I'm a PhD Candidate in Computer Science, from The City University of New York, advised by Prof [Lei Xie](http://compsci.hunter.cuny.edu/~leixie/) 
